config/routes.rb
Rails.application.routes.draw do

  devise_for :users , :controllers => {registrations: 'registrations'}

  root 'user#index_02'

  get '/device/:id', to: 'user#map' , as: 'device_map'

  post 'ledToggle/:id', to: 'user#ledToggle' , as: 'function_led'

  post 'gpsToggle/:id', to: 'user#gpsToggle' , as: 'function_gps'

  resources :user do
  end

  resources :config

end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :user
end

app/models/point.rb
class Point < ActiveRecord::Base
   belongs_to :tracksegment

   #attr_accessible :description, :elevation, :latitude, :longitude, :name, :point_created_at

   def latlgn
      [self.latitude, self.longitude]
   end



end

app/models/track.rb
class Track < ActiveRecord::Base
  before_save :parse_file

  #attr_accessible :name, :gpx

  has_attached_file :gpx

  has_many :tracksegments, :dependent => :destroy
  has_many :points, :through => :tracksegments


  def polyline_points

    self.points.map(&amp::latlgn)

  end

  def polyline
    Polylines::Encoder.encode_points(self.polyline_points)
  end

  private

  def parse_file
    tempfile = gpx.queued_for_write[:original]
    doc = Nokogiri::XML(tempfile)
    parse_xml(doc)
  end

  def parse_xml(doc)
    doc.root.elements.each do |node|
      parse_tracks(node)
    end
  end

  def parse_tracks(node)
    if node.node_name.eql? 'trk'
      node.elements.each do |node|
        parse_track_segments(node)
      end
    end
  end

  def parse_track_segments(node)
    if node.node_name.eql? 'trkseg'
      tmp_segment = Tracksegment.new
      node.elements.each do |node|
        parse_points(node,tmp_segment)
      end
      self.tracksegments << tmp_segment
    end
  end

  def parse_points(node,tmp_segment)
    if node.node_name.eql? 'trkpt'
      tmp_point = Point.new
      tmp_point.latitude = node.attr("lat")
      tmp_point.longitude = node.attr("lon")
      node.elements.each do |node|
        tmp_point.name = node.text.to_s if node.name.eql? 'name'
        tmp_point.elevation = node.text.to_s if node.name.eql? 'ele'
        tmp_point.description = node.text.to_s if node.name.eql? 'desc'
        tmp_point.point_created_at = node.text.to_s if node.name.eql? 'time'
      end
      tmp_segment.points << tmp_point
    end
  end

end

app/models/tracksegment.rb
class Tracksegment < ActiveRecord::Base
  belongs_to :track
  has_many :points, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base


  before_save :split_devices
  after_create :add_user_to_cloud

# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable


  # associations
  has_many :devices

  #Devise stuff
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #validations
  validates :username , presence: true , uniqueness: true
  #validates :tracker_id
  # validates :access_token, after_create: { presence: true , uniqueness: true  }

#varibale configurations

  serialize :tracker_id,Array



  private

  def split_devices

    if self.tracker_id.blank?
      self.tracker_id << 204
    #elsif self.changed?


    # elsif self.tracker_id.include? :username
    #   self.tracker_id.clear
    #   self.tracker_id << self.lastname
    end
  end



  def add_user_to_cloud

    request = Typhoeus::Request.new('https://api.particle.io/v1/orgs/subtletrax/customers',
                                     method: :post,
                                     body: {email: self.email , no_password: 'true'},
                                    userpwd: "#{ENV['client_id']}:#{ENV['client_secret']}")

    request.run

    response= request.response.body
    response_json = JSON.parse(response)

    puts response_json.to_yaml

    self.update(:access_token => response_json['access_token'])
    self.update(:refresh_token => response_json['refresh_token'])
    #self.save


    #   set_scoped_access = Typhoeus::Request.new('https://api.particle.io/oauth/token',
  #                                             method: :post,
  #                                             body: {scope: "customer=#{self.email}",
  #                                                    grant_type: 'client_credentials',
  #                                                    expires_in: '7776000'},
  #                                             userpwd: "#{ENV{'client_id'}}:#{ENV{'client_secret'}}")
  #
  # set_scoped_access.run
  #
  # response= set_scoped_access.response.body
  # response_json = JSON.parse(response)
  # self.access_token = response_json['access_token'][0]
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/config_controller.rb
class ConfigController < ApplicationController
  def index

  end
end

app/controllers/device_controller.rb
class DeviceController < ApplicationController
  before_action :set_devices
  #before_action :authenticate_user!

  def index

  end

  def show

   # @device = @device.User.find(params[:id])


  end

  def map

    if @devices.exists?

      @device = RubySpark::Device.new(params[:id])

      @gpsCoords = @device.variable('gpsPos').split(',')

      @lat = @gpsCoords[0]

      @lng = @gpsCoords[1]

    else
      @device = [{:gpsPos => "empty , empty" }]

      @gpsCoords = @device.variable('gpsPos').split(',')

      @lat = @gpsCoords[0]

      @lng = @gpsCoords[1]
    end



  end

  private

    def set_devices

      @devices = Particle.devices



    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private


  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :firstname, :lastname)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password , :tracker_id,   :firstname, :lastname)
  end
end

app/controllers/track_controller.rb
class TrackController < ApplicationController
  def show

  end
  # def show
  #   @track = Track.find(params[:id])
  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json {
  #       render :json =>  @track.to_json(:methods => :polyline,
  #                                       :only => :name)
  #     }

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  #before_action :set_devices

  # before_action :authenticate_user! , except: :index
  before_action :authenticate_user!

  after_action :session_config



  def index

    #@devices

  end

  def show

    @user = User.find(params[:id])


  end

  def update
    @user = User.update(user_params)

  end

  def map
    @device = RubySpark::Device.new(params[:id])

    @gpsCoords = @device.variable('gpsPos').split(',')

    @lat = @gpsCoords[0]

    @lng = @gpsCoords[1]

  end

  def gpsToggle

    @device = RubySpark::Device.new(params[:id])

    if @device.variable('gpsPos') == 'off'

      @device.function('TrackRT', 'on')

    elsif @device.variable('gpsPos') == 'on'

      @device.function('TrackRT', 'SF')

         elsif @device.variable('gpsPos') == 'SF'


                @device.function('TrackRT', 'on')


    end

    redirect_to device_map_path(params[:id])

  end

  def ledToggle

    @device = RubySpark::Device.new(params[:id])

    if @device.variable('led') == 'off'

      @device.function('led', 'on')

    else

      @device.function('led', 'off')

    end

    redirect_to device_map_path(params[:id])

  end


  private

  def user_params

    params.require(:user).permit(:email, :password, :password_confirmation, :username, :tracker_id)

  end

  def set_devices

    @devices = Particle.devices

  end

  def session_config

    if user_signed_in?

      session[:accessToken] = current_user.access_token

    else

      redirect_to new_user_session_path

    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/device_helper.rb
module DeviceHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/track_helper.rb
module TrackHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/config/index.html.erb
<div>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
</div>

<h1>YOU MADE IT!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BikeTrax</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>


<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['google_map_key']%>&signed_in=true"></script>
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

</html>

app/views/user/index.html.erb
  <div class="col-md-9" role="main" style="margin: auto">
  <div class="panel panel-primary" style="width: 100%">
      <h2 class="panel-heading">List of Devices</h2>
      <div class="panel-body">
        <% @devices.each do |device| %>
            <table class='table' style="alignment:center" >
              <tr>
                <th>Name</th>
                <th>Device ID</th>
                <th>Recent Position</th>
                <th>Power Mode</th>
                <th>Status</th>

              </tr>
              <tr href="#">
                <td><%= link_to device.get_attributes[:name], device_map_path(device.get_attributes[:id]) %></td>
                <td><%= link_to device.get_attributes[:id], device_map_path(device.get_attributes[:id]) %></td>
                <td><%= device.variable('gpsPos')%></td>
                <td><%= device.variable('PowerMode')%></td>
                <!--<td><%= device.get_attributes[:connected] ? 'Online' : 'Off-line' %></td>-->
                <% if device.get_attributes[:connected]%>
                    <td>
                      <a style="color:#2EFE2E">Online</a>
                    </td>
                <% else %>
                    <td>
                    <a style="color:red">Offline</a>
                    </td>
                <%end%>
              </tr>
            </table>
        <% end %>
      </div>

    </div>
  </div>

app/views/user/index_02.html.erb
<div>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>

</div>

app/views/user/map.html.erb
<h1><%= @gpsCoords %></h1>
<h3><%= @lat %></h3>
<h3><%= @lng %></h3>

 <title>Lat/Lng Object Literal</title>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <style>

    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }
    #map {
      height: 50%;
      width: 75%;
    }

  </style>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['google_map_key']%>"></script>
  <script>
    // In this example, we center the map, and add a marker, using a LatLng object
    // literal instead of a google.maps.LatLng object. LatLng object literals are
    // a convenient way to add a LatLng coordinate and, in most cases, can be used
    // in place of a google.maps.LatLng object.

    var map;
    function initialize() {
      var mapOptions = {
        zoom: 13,
        center: {lat: <%= @lat %>, lng: <%= @lng %>}
      };
      map = new google.maps.Map(document.getElementById('map'),
          mapOptions);

      var marker = new google.maps.Marker({
        // The below line is equivalent to writing:
        // position: new google.maps.LatLng(-34.397, 150.644)
        //position: {lat: -34.397, lng: 150.644},
        position: {lat: <%= @lat %>, lng: <%= @lng %>},
        map: map
      });

      // You can use a LatLng literal in place of a google.maps.LatLng object when
      // creating the Marker object. Once the Marker object is instantiated, its
      // position will be available as a google.maps.LatLng object. In this case,
      // we retrieve the marker's position using the
      // google.maps.LatLng.getPosition() method.
      var infowindow = new google.maps.InfoWindow({
        content: '<p>Marker Location:' + marker.getPosition() + '</p>'
      });

      google.maps.event.addListener(marker, 'click', function() {
        infowindow.open(map, marker);
      });
    }

    google.maps.event.addDomListener(window, 'load', initialize);

  </script>

</head>
<div id="map"></div>

<% if @device.variable('led')== 'on' %>
    <%= button_to "Toggle LED off", function_led_path(params[:id]) , class: 'btn btn-primary' %>
<% else %>
    <%= button_to "Toggle LED on", function_led_path(params[:id]) , class: 'btn btn-primary' %>
<% end %>